### ISSUE TITLE
Assessment Bugs

### ISSUE THREAD

**Issue by micklwl** [CS2113-AY1819S1-F10-1/main#161]
AddAssessmentStats:
1. Exam takers can be any number. i.e smaller than absentees and people who passed.
2. Max-min score check not enforced. Message displays them opposite way.

AddGrades:
1. Wrong error message when assess index is out of bounds.
2. Maybe means addscore instead since its stored as int?

DeleteAssess:
1. No exception caught when assess index is out of bounds.

AddAssess:
1. Does not save. Performed addassess followed by exit. Reopen to see no assess.

**Comment by Meg1456** [comment]
Remaining Bugs To Fix: 

AddAssessmentStats:
Exam takers can be any number. i.e smaller than absentees and people who passed.
Max-min score check not enforced. Message displays them opposite way.

AddGrades:
Wrong error message when assess index is out of bounds.
Maybe means addscore instead since its stored as int?

AddAssess:
Does not save. Performed addassess followed by exit. Reopen to see no assess.

**Comment by Meg1456** [comment]
Remaining Bugs To Fix: 

AddAssessmentStats: 
Updating a pre-existing statistic 

AddAssess:
Does not save. Performed addassess followed by exit. Reopen to see no assess.
